[[redirects]]
  from = "https://pirate-courses.ru/*"
  to = "https://pirate-courses.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.pirate-courses.ru/*"
  to = "https://pirate-courses.netlify.app/:splat"
  status = 301
  force = true